version: '3.8'
services:
  mongodb:
    image: mongo:alpine
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: anhle@!*2025
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: