version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats_jetstream
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    command: ["-js"]
    restart: unless-stopped
