version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis_secure
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=anhle@!*2025
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no", "--requirepass", "anhle@!*2025"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
